apiVersion: v1
kind: Service
metadata:
  name: grafana-cluster-ip-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-external-name-service
  namespace: nvg-cdp
spec:
  type: ExternalName
  externalName: grafana-cluster-ip-service.default