apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: kylo-ren-cloud-tls
spec:
  secretName: kylo-ren-3f10f1910b7ec0b1bd973da20db66b8f-0000.us-south.containers.appdomain-cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kylo-ren-cloud-tls
  dnsNames:
    - kylo-ren-3f10f1910b7ec0b1bd973da20db66b8f-0000.us-south.containers.appdomain.cloud