apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cdp-hpa
  namespace: nvg-cdp
spec:
  minReplicas: 3
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  targetCPUUtilizationPercentage: 40